import './globals.css';
import { Navbar, FooterSection } from '@nextjs-template/ui';
import Page from './page';

export const metadata = {
  title: 'Welcome to ',
  description: 'Generated by create-nx-workspace',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="flex min-h-screen flex-col">
      <Navbar />
         <main className="flex-1">{children}</main>
      <FooterSection />
      </body>
    </html>
  )
}
