import './globals.css';
import Navbar from './components/Navbar';
import FooterSection from './components/Footer';

export const metadata = {
  title: 'Welcome to ',
  description: 'Generated by create-nx-workspace',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <Navbar />
      <body className="flex min-h-screen flex-col">
         <main className="flex-1">{children}</main>
      </body>
      <FooterSection />
    </html>
  )
}
